add prime mode logic to the provisioning-tests script (#1839)

diff --git a/scripts/provisioning-tests b/scripts/provisioning-tests
--- a/scripts/provisioning-tests
+++ b/scripts/provisioning-tests
@@ -82,6 +82,17 @@ if [ -z "${SOME_K8S_VERSION}" ]; then
   export SOME_K8S_VERSION
 fi
 
+source scripts/prime-route
+
+
+if [[ "${PRIME_MODE}" == "1" ]]; then
+  if [[ -z "${CATTLE_AGENT_IMAGE}" ]]; then
+    echo "ERROR: In Prime mode (PRIME_MODE=1), CATTLE_AGENT_IMAGE must be set."
+    exit 1
+  fi
+  echo "Prime mode enabled (rancher-agent=${CATTLE_AGENT_IMAGE}); proceeding with provisioning tests."
+fi
+
 # Copy rancher provisioning tests, and enter directory they exist
 source ./scripts/fetch-provisioning-tests
 
